// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: access_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccessToken = `-- name: CreateAccessToken :one
insert into access_tokens (session_id, token_hash, expires_at)
values ($1, $2, $3)
returning id, session_id, token_hash, expires_at, created_at
`

type CreateAccessTokenParams struct {
	SessionID pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) (AccessToken, error) {
	row := q.db.QueryRow(ctx, createAccessToken, arg.SessionID, arg.TokenHash, arg.ExpiresAt)
	var i AccessToken
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAccessContext = `-- name: GetAccessContext :one
select s.id as session_id, s.client_public_key, u.id as user_id, u.role, u.status
from access_tokens at
join sessions s on s.id = at.session_id
join users u on u.id = s.user_id
where at.token_hash = $1
  and at.expires_at > now()
  and s.revoked_at is null
  and s.expires_at > now()
`

type GetAccessContextRow struct {
	SessionID       pgtype.UUID
	ClientPublicKey []byte
	UserID          pgtype.UUID
	Role            string
	Status          string
}

func (q *Queries) GetAccessContext(ctx context.Context, tokenHash string) (GetAccessContextRow, error) {
	row := q.db.QueryRow(ctx, getAccessContext, tokenHash)
	var i GetAccessContextRow
	err := row.Scan(
		&i.SessionID,
		&i.ClientPublicKey,
		&i.UserID,
		&i.Role,
		&i.Status,
	)
	return i, err
}
