// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: access_logs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPublicKeyByFingerprint = `-- name: GetPublicKeyByFingerprint :one
select id, user_id, label, key_type, key_blob, fingerprint, created_at from public_keys where fingerprint = $1
`

func (q *Queries) GetPublicKeyByFingerprint(ctx context.Context, fingerprint string) (PublicKey, error) {
	row := q.db.QueryRow(ctx, getPublicKeyByFingerprint, fingerprint)
	var i PublicKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.KeyType,
		&i.KeyBlob,
		&i.Fingerprint,
		&i.CreatedAt,
	)
	return i, err
}

const insertSSHAccessLog = `-- name: InsertSSHAccessLog :exec
insert into ssh_access_logs (host_id, hostname, public_key_id, account, allowed, at, fingerprint)
values ($1, $2, $3, $4, $5, $6, $7)
`

type InsertSSHAccessLogParams struct {
	HostID      pgtype.UUID
	Hostname    string
	PublicKeyID pgtype.UUID
	Account     string
	Allowed     bool
	At          pgtype.Timestamptz
	Fingerprint string
}

func (q *Queries) InsertSSHAccessLog(ctx context.Context, arg InsertSSHAccessLogParams) error {
	_, err := q.db.Exec(ctx, insertSSHAccessLog,
		arg.HostID,
		arg.Hostname,
		arg.PublicKeyID,
		arg.Account,
		arg.Allowed,
		arg.At,
		arg.Fingerprint,
	)
	return err
}

const listHostAccessLogs = `-- name: ListHostAccessLogs :many
select account, allowed, fingerprint, at from ssh_access_logs
where host_id = $1 order by at desc limit 100
`

type ListHostAccessLogsRow struct {
	Account     string
	Allowed     bool
	Fingerprint string
	At          pgtype.Timestamptz
}

func (q *Queries) ListHostAccessLogs(ctx context.Context, hostID pgtype.UUID) ([]ListHostAccessLogsRow, error) {
	rows, err := q.db.Query(ctx, listHostAccessLogs, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHostAccessLogsRow{}
	for rows.Next() {
		var i ListHostAccessLogsRow
		if err := rows.Scan(
			&i.Account,
			&i.Allowed,
			&i.Fingerprint,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
