// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: access_logs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPublicKeyByFingerprint = `-- name: GetPublicKeyByFingerprint :one
select id, user_id, label, key_type, key_blob, fingerprint, created_at from public_keys where fingerprint = $1
`

func (q *Queries) GetPublicKeyByFingerprint(ctx context.Context, fingerprint string) (PublicKey, error) {
	row := q.db.QueryRow(ctx, getPublicKeyByFingerprint, fingerprint)
	var i PublicKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.KeyType,
		&i.KeyBlob,
		&i.Fingerprint,
		&i.CreatedAt,
	)
	return i, err
}

const insertSSHAccessLog = `-- name: InsertSSHAccessLog :exec
insert into ssh_access_logs (host_id, public_key_id, account, allowed, at)
values ($1, $2, $3, $4, $5)
`

type InsertSSHAccessLogParams struct {
	HostID      pgtype.UUID
	PublicKeyID pgtype.UUID
	Account     string
	Allowed     bool
	At          pgtype.Timestamptz
}

func (q *Queries) InsertSSHAccessLog(ctx context.Context, arg InsertSSHAccessLogParams) error {
	_, err := q.db.Exec(ctx, insertSSHAccessLog,
		arg.HostID,
		arg.PublicKeyID,
		arg.Account,
		arg.Allowed,
		arg.At,
	)
	return err
}
