// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: enrollment.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEnrollmentToken = `-- name: CreateEnrollmentToken :one
insert into enrollment_tokens (token_hash, label, accounts, created_by, expires_at)
values ($1, $2, $3, $4, $5)
returning id, token_hash, label, accounts, created_by, expires_at, used_at, host_id, created_at
`

type CreateEnrollmentTokenParams struct {
	TokenHash string
	Label     pgtype.Text
	Accounts  []string
	CreatedBy pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateEnrollmentToken(ctx context.Context, arg CreateEnrollmentTokenParams) (EnrollmentToken, error) {
	row := q.db.QueryRow(ctx, createEnrollmentToken,
		arg.TokenHash,
		arg.Label,
		arg.Accounts,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i EnrollmentToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Label,
		&i.Accounts,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.HostID,
		&i.CreatedAt,
	)
	return i, err
}

const getEnrollmentToken = `-- name: GetEnrollmentToken :one
select id, token_hash, label, accounts, created_by, expires_at, used_at, host_id, created_at from enrollment_tokens where token_hash = $1
`

func (q *Queries) GetEnrollmentToken(ctx context.Context, tokenHash string) (EnrollmentToken, error) {
	row := q.db.QueryRow(ctx, getEnrollmentToken, tokenHash)
	var i EnrollmentToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Label,
		&i.Accounts,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.HostID,
		&i.CreatedAt,
	)
	return i, err
}

const markTokenUsed = `-- name: MarkTokenUsed :exec
update enrollment_tokens set used_at = now(), host_id = $2 where id = $1
`

type MarkTokenUsedParams struct {
	ID     pgtype.UUID
	HostID pgtype.UUID
}

func (q *Queries) MarkTokenUsed(ctx context.Context, arg MarkTokenUsedParams) error {
	_, err := q.db.Exec(ctx, markTokenUsed, arg.ID, arg.HostID)
	return err
}
