// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: grants.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGrant = `-- name: CreateGrant :one
insert into grants (user_id, permission, target_kind, target_id, granted_by)
values ($1, $2, $3, $4, $5)
returning id, user_id, permission, target_kind, target_id, granted_by, created_at, revoked_at
`

type CreateGrantParams struct {
	UserID     pgtype.UUID
	Permission string
	TargetKind string
	TargetID   pgtype.UUID
	GrantedBy  pgtype.UUID
}

func (q *Queries) CreateGrant(ctx context.Context, arg CreateGrantParams) (Grant, error) {
	row := q.db.QueryRow(ctx, createGrant,
		arg.UserID,
		arg.Permission,
		arg.TargetKind,
		arg.TargetID,
		arg.GrantedBy,
	)
	var i Grant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Permission,
		&i.TargetKind,
		&i.TargetID,
		&i.GrantedBy,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const groupHostIDs = `-- name: GroupHostIDs :many
select resource_id from group_resources
where group_id = $1 and resource_kind = 'host'
`

func (q *Queries) GroupHostIDs(ctx context.Context, groupID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, groupHostIDs, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var resource_id pgtype.UUID
		if err := rows.Scan(&resource_id); err != nil {
			return nil, err
		}
		items = append(items, resource_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertGrantAudit = `-- name: InsertGrantAudit :exec
insert into grant_audit_logs
  (action, grant_id, actor_id, actor_email, subject_id, subject_email, permission, target_kind, target_id)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertGrantAuditParams struct {
	Action       string
	GrantID      pgtype.UUID
	ActorID      pgtype.UUID
	ActorEmail   string
	SubjectID    pgtype.UUID
	SubjectEmail string
	Permission   string
	TargetKind   string
	TargetID     pgtype.UUID
}

func (q *Queries) InsertGrantAudit(ctx context.Context, arg InsertGrantAuditParams) error {
	_, err := q.db.Exec(ctx, insertGrantAudit,
		arg.Action,
		arg.GrantID,
		arg.ActorID,
		arg.ActorEmail,
		arg.SubjectID,
		arg.SubjectEmail,
		arg.Permission,
		arg.TargetKind,
		arg.TargetID,
	)
	return err
}

const listGrantAudit = `-- name: ListGrantAudit :many
select id, action, grant_id, actor_id, actor_email, subject_id, subject_email,
       permission, target_kind, target_id, at
from grant_audit_logs
order by at desc
limit 100
`

func (q *Queries) ListGrantAudit(ctx context.Context) ([]GrantAuditLog, error) {
	rows, err := q.db.Query(ctx, listGrantAudit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GrantAuditLog{}
	for rows.Next() {
		var i GrantAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.GrantID,
			&i.ActorID,
			&i.ActorEmail,
			&i.SubjectID,
			&i.SubjectEmail,
			&i.Permission,
			&i.TargetKind,
			&i.TargetID,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrants = `-- name: ListGrants :many
select g.id, g.permission, g.target_kind, g.target_id, g.created_at,
       u.id as user_id, u.email as user_email
from grants g
join users u on u.id = g.user_id
where g.revoked_at is null
order by g.created_at desc
`

type ListGrantsRow struct {
	ID         pgtype.UUID
	Permission string
	TargetKind string
	TargetID   pgtype.UUID
	CreatedAt  pgtype.Timestamptz
	UserID     pgtype.UUID
	UserEmail  string
}

func (q *Queries) ListGrants(ctx context.Context) ([]ListGrantsRow, error) {
	rows, err := q.db.Query(ctx, listGrants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGrantsRow{}
	for rows.Next() {
		var i ListGrantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Permission,
			&i.TargetKind,
			&i.TargetID,
			&i.CreatedAt,
			&i.UserID,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeGrant = `-- name: RevokeGrant :one
update grants set revoked_at = now()
where id = $1 and revoked_at is null
returning id, user_id, permission, target_kind, target_id, granted_by, created_at, revoked_at
`

func (q *Queries) RevokeGrant(ctx context.Context, id pgtype.UUID) (Grant, error) {
	row := q.db.QueryRow(ctx, revokeGrant, id)
	var i Grant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Permission,
		&i.TargetKind,
		&i.TargetID,
		&i.GrantedBy,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}
