// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: groups.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addGroupResource = `-- name: AddGroupResource :exec
insert into group_resources (group_id, resource_kind, resource_id)
values ($1, $2, $3)
on conflict do nothing
`

type AddGroupResourceParams struct {
	GroupID      pgtype.UUID
	ResourceKind string
	ResourceID   pgtype.UUID
}

func (q *Queries) AddGroupResource(ctx context.Context, arg AddGroupResourceParams) error {
	_, err := q.db.Exec(ctx, addGroupResource, arg.GroupID, arg.ResourceKind, arg.ResourceID)
	return err
}

const createGroup = `-- name: CreateGroup :one
insert into resource_groups (name, description) values ($1, $2) returning id, name, description, created_at
`

type CreateGroupParams struct {
	Name        string
	Description string
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (ResourceGroup, error) {
	row := q.db.QueryRow(ctx, createGroup, arg.Name, arg.Description)
	var i ResourceGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :execrows
delete from resource_groups where id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGroup, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGroup = `-- name: GetGroup :one
select id, name, description, created_at from resource_groups where id = $1
`

func (q *Queries) GetGroup(ctx context.Context, id pgtype.UUID) (ResourceGroup, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	var i ResourceGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listGroupResources = `-- name: ListGroupResources :many
select resource_kind, resource_id, added_at
from group_resources where group_id = $1 order by added_at
`

type ListGroupResourcesRow struct {
	ResourceKind string
	ResourceID   pgtype.UUID
	AddedAt      pgtype.Timestamptz
}

func (q *Queries) ListGroupResources(ctx context.Context, groupID pgtype.UUID) ([]ListGroupResourcesRow, error) {
	rows, err := q.db.Query(ctx, listGroupResources, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupResourcesRow{}
	for rows.Next() {
		var i ListGroupResourcesRow
		if err := rows.Scan(&i.ResourceKind, &i.ResourceID, &i.AddedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
select id, name, description, created_at from resource_groups order by name
`

func (q *Queries) ListGroups(ctx context.Context) ([]ResourceGroup, error) {
	rows, err := q.db.Query(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResourceGroup{}
	for rows.Next() {
		var i ResourceGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadableGroups = `-- name: ListReadableGroups :many
select distinct rg.id, rg.name, rg.description, rg.created_at
from resource_groups rg
join grants g on g.permission = 'group.read' and g.revoked_at is null
  and g.target_kind = 'group' and g.target_id = rg.id
where g.user_id = $1
order by rg.name
`

func (q *Queries) ListReadableGroups(ctx context.Context, userID pgtype.UUID) ([]ResourceGroup, error) {
	rows, err := q.db.Query(ctx, listReadableGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResourceGroup{}
	for rows.Next() {
		var i ResourceGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGroupResource = `-- name: RemoveGroupResource :execrows
delete from group_resources
where group_id = $1 and resource_kind = $2 and resource_id = $3
`

type RemoveGroupResourceParams struct {
	GroupID      pgtype.UUID
	ResourceKind string
	ResourceID   pgtype.UUID
}

func (q *Queries) RemoveGroupResource(ctx context.Context, arg RemoveGroupResourceParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeGroupResource, arg.GroupID, arg.ResourceKind, arg.ResourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeGroupGrants = `-- name: RevokeGroupGrants :exec
update grants set revoked_at = now()
where target_kind = 'group' and target_id = $1 and revoked_at is null
`

func (q *Queries) RevokeGroupGrants(ctx context.Context, targetID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeGroupGrants, targetID)
	return err
}
