// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: hosts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHost = `-- name: CreateHost :one
insert into hosts (name, hostname, identity_key, accounts, machine_id)
values ($1, $2, $3, $4, $5)
returning id, name, hostname, identity_key, accounts, status, machine_id, last_seq, enrolled_at, last_seen_at
`

type CreateHostParams struct {
	Name        string
	Hostname    string
	IdentityKey string
	Accounts    []string
	MachineID   pgtype.Text
}

func (q *Queries) CreateHost(ctx context.Context, arg CreateHostParams) (Host, error) {
	row := q.db.QueryRow(ctx, createHost,
		arg.Name,
		arg.Hostname,
		arg.IdentityKey,
		arg.Accounts,
		arg.MachineID,
	)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.IdentityKey,
		&i.Accounts,
		&i.Status,
		&i.MachineID,
		&i.LastSeq,
		&i.EnrolledAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getActiveHostByMachineID = `-- name: GetActiveHostByMachineID :one
select id, name, hostname, identity_key, accounts, status, machine_id, last_seq, enrolled_at, last_seen_at from hosts where machine_id = $1 and status = 'active'
`

func (q *Queries) GetActiveHostByMachineID(ctx context.Context, machineID pgtype.Text) (Host, error) {
	row := q.db.QueryRow(ctx, getActiveHostByMachineID, machineID)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.IdentityKey,
		&i.Accounts,
		&i.Status,
		&i.MachineID,
		&i.LastSeq,
		&i.EnrolledAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getHostByID = `-- name: GetHostByID :one
select id, name, hostname, identity_key, accounts, status, machine_id, last_seq, enrolled_at, last_seen_at from hosts where id = $1
`

func (q *Queries) GetHostByID(ctx context.Context, id pgtype.UUID) (Host, error) {
	row := q.db.QueryRow(ctx, getHostByID, id)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.IdentityKey,
		&i.Accounts,
		&i.Status,
		&i.MachineID,
		&i.LastSeq,
		&i.EnrolledAt,
		&i.LastSeenAt,
	)
	return i, err
}

const listHosts = `-- name: ListHosts :many
select id, name, hostname, accounts, status, enrolled_at, last_seen_at
from hosts order by name
`

type ListHostsRow struct {
	ID         pgtype.UUID
	Name       string
	Hostname   string
	Accounts   []string
	Status     string
	EnrolledAt pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
}

func (q *Queries) ListHosts(ctx context.Context) ([]ListHostsRow, error) {
	rows, err := q.db.Query(ctx, listHosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHostsRow{}
	for rows.Next() {
		var i ListHostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Hostname,
			&i.Accounts,
			&i.Status,
			&i.EnrolledAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextHostSeq = `-- name: NextHostSeq :one
update hosts set last_seq = last_seq + 1 where id = $1 returning last_seq
`

func (q *Queries) NextHostSeq(ctx context.Context, id pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, nextHostSeq, id)
	var last_seq int64
	err := row.Scan(&last_seq)
	return last_seq, err
}

const setHostStatus = `-- name: SetHostStatus :execrows
update hosts set status = $2 where id = $1
`

type SetHostStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) SetHostStatus(ctx context.Context, arg SetHostStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setHostStatus, arg.ID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchHostSeen = `-- name: TouchHostSeen :exec
update hosts set last_seen_at = now() where id = $1
`

func (q *Queries) TouchHostSeen(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchHostSeen, id)
	return err
}
