// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: hosts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHost = `-- name: CreateHost :one
insert into hosts (name, hostname, identity_key, accounts)
values ($1, $2, $3, $4)
returning id, name, hostname, identity_key, accounts, status, enrolled_at, last_seen_at
`

type CreateHostParams struct {
	Name        string
	Hostname    string
	IdentityKey string
	Accounts    []string
}

func (q *Queries) CreateHost(ctx context.Context, arg CreateHostParams) (Host, error) {
	row := q.db.QueryRow(ctx, createHost,
		arg.Name,
		arg.Hostname,
		arg.IdentityKey,
		arg.Accounts,
	)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.IdentityKey,
		&i.Accounts,
		&i.Status,
		&i.EnrolledAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getHostByID = `-- name: GetHostByID :one
select id, name, hostname, identity_key, accounts, status, enrolled_at, last_seen_at from hosts where id = $1
`

func (q *Queries) GetHostByID(ctx context.Context, id pgtype.UUID) (Host, error) {
	row := q.db.QueryRow(ctx, getHostByID, id)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.IdentityKey,
		&i.Accounts,
		&i.Status,
		&i.EnrolledAt,
		&i.LastSeenAt,
	)
	return i, err
}

const touchHostSeen = `-- name: TouchHostSeen :exec
update hosts set last_seen_at = now() where id = $1
`

func (q *Queries) TouchHostSeen(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchHostSeen, id)
	return err
}
