// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: identities.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIdentity = `-- name: CreateIdentity :one
insert into identities (user_id, provider, external_id, password_hash)
values ($1, $2, $3, $4)
returning id, user_id, provider, external_id, password_hash, created_at, last_login_at, failed_logins, last_failed_at, locked_until
`

type CreateIdentityParams struct {
	UserID       pgtype.UUID
	Provider     string
	ExternalID   string
	PasswordHash pgtype.Text
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (Identity, error) {
	row := q.db.QueryRow(ctx, createIdentity,
		arg.UserID,
		arg.Provider,
		arg.ExternalID,
		arg.PasswordHash,
	)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ExternalID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.FailedLogins,
		&i.LastFailedAt,
		&i.LockedUntil,
	)
	return i, err
}

const getIdentity = `-- name: GetIdentity :one
select id, user_id, provider, external_id, password_hash, created_at, last_login_at, failed_logins, last_failed_at, locked_until from identities where provider = $1 and external_id = $2
`

type GetIdentityParams struct {
	Provider   string
	ExternalID string
}

func (q *Queries) GetIdentity(ctx context.Context, arg GetIdentityParams) (Identity, error) {
	row := q.db.QueryRow(ctx, getIdentity, arg.Provider, arg.ExternalID)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ExternalID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.FailedLogins,
		&i.LastFailedAt,
		&i.LockedUntil,
	)
	return i, err
}

const resetLoginFailures = `-- name: ResetLoginFailures :exec
update identities set failed_logins = 0, locked_until = null where id = $1
`

func (q *Queries) ResetLoginFailures(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resetLoginFailures, id)
	return err
}

const setLoginFailure = `-- name: SetLoginFailure :exec
update identities set failed_logins = $2, locked_until = $3, last_failed_at = now()
where id = $1
`

type SetLoginFailureParams struct {
	ID           pgtype.UUID
	FailedLogins int32
	LockedUntil  pgtype.Timestamptz
}

func (q *Queries) SetLoginFailure(ctx context.Context, arg SetLoginFailureParams) error {
	_, err := q.db.Exec(ctx, setLoginFailure, arg.ID, arg.FailedLogins, arg.LockedUntil)
	return err
}

const touchIdentityLogin = `-- name: TouchIdentityLogin :exec
update identities set last_login_at = now() where id = $1
`

func (q *Queries) TouchIdentityLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchIdentityLogin, id)
	return err
}

const updatePasswordIdentity = `-- name: UpdatePasswordIdentity :exec
update identities set password_hash = $2
where user_id = $1 and provider = 'password'
`

type UpdatePasswordIdentityParams struct {
	UserID       pgtype.UUID
	PasswordHash pgtype.Text
}

func (q *Queries) UpdatePasswordIdentity(ctx context.Context, arg UpdatePasswordIdentityParams) error {
	_, err := q.db.Exec(ctx, updatePasswordIdentity, arg.UserID, arg.PasswordHash)
	return err
}
