// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: invitations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvitation = `-- name: CreateInvitation :one
insert into invitations (email, role, token_hash, invited_by, expires_at)
values ($1, $2, $3, $4, $5)
returning id, email, role, token_hash, invited_by, expires_at, accepted_at, created_at
`

type CreateInvitationParams struct {
	Email     string
	Role      string
	TokenHash string
	InvitedBy pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInvitation = `-- name: DeleteInvitation :execrows
delete from invitations where id = $1 and accepted_at is null
`

func (q *Queries) DeleteInvitation(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInvitation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getInvitationByTokenHash = `-- name: GetInvitationByTokenHash :one
select id, email, role, token_hash, invited_by, expires_at, accepted_at, created_at from invitations where token_hash = $1
`

func (q *Queries) GetInvitationByTokenHash(ctx context.Context, tokenHash string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByTokenHash, tokenHash)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingInvitations = `-- name: ListPendingInvitations :many
select id, email, role, invited_by, expires_at, created_at
from invitations
where accepted_at is null and expires_at > now()
order by created_at desc
`

type ListPendingInvitationsRow struct {
	ID        pgtype.UUID
	Email     string
	Role      string
	InvitedBy pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListPendingInvitations(ctx context.Context) ([]ListPendingInvitationsRow, error) {
	rows, err := q.db.Query(ctx, listPendingInvitations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingInvitationsRow{}
	for rows.Next() {
		var i ListPendingInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.InvitedBy,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInvitationAccepted = `-- name: MarkInvitationAccepted :exec
update invitations set accepted_at = now() where id = $1
`

func (q *Queries) MarkInvitationAccepted(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markInvitationAccepted, id)
	return err
}

const refreshInvitationToken = `-- name: RefreshInvitationToken :one
update invitations set token_hash = $2, expires_at = $3
where id = $1 and accepted_at is null
returning id, email, role, token_hash, invited_by, expires_at, accepted_at, created_at
`

type RefreshInvitationTokenParams struct {
	ID        pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) RefreshInvitationToken(ctx context.Context, arg RefreshInvitationTokenParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, refreshInvitationToken, arg.ID, arg.TokenHash, arg.ExpiresAt)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}
