// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccessToken struct {
	ID        pgtype.UUID
	SessionID pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type EnrollmentToken struct {
	ID        pgtype.UUID
	TokenHash string
	Label     pgtype.Text
	Accounts  []string
	CreatedBy pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	HostID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type Grant struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Permission string
	TargetKind string
	TargetID   pgtype.UUID
	GrantedBy  pgtype.UUID
	CreatedAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

type GrantAuditLog struct {
	ID           pgtype.UUID
	Action       string
	GrantID      pgtype.UUID
	ActorID      pgtype.UUID
	ActorEmail   string
	SubjectID    pgtype.UUID
	SubjectEmail string
	Permission   string
	TargetKind   string
	TargetID     pgtype.UUID
	At           pgtype.Timestamptz
}

type GroupResource struct {
	GroupID      pgtype.UUID
	ResourceKind string
	ResourceID   pgtype.UUID
	AddedAt      pgtype.Timestamptz
}

type Host struct {
	ID             pgtype.UUID
	Name           string
	Hostname       string
	IdentityKey    string
	EncryptionKey  string
	Accounts       []string
	Status         string
	MachineID      pgtype.Text
	LastSeq        int64
	LastSetSeq     int64
	AgentVersion   string
	DesiredVersion string
	EnrolledAt     pgtype.Timestamptz
	LastSeenAt     pgtype.Timestamptz
}

type HostSetBinding struct {
	HostID    pgtype.UUID
	SetID     pgtype.UUID
	AsUser    pgtype.Text
	GrantedBy pgtype.UUID
	CreatedAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

type Identity struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Provider     string
	ExternalID   string
	PasswordHash pgtype.Text
	CreatedAt    pgtype.Timestamptz
	LastLoginAt  pgtype.Timestamptz
	FailedLogins int32
	LastFailedAt pgtype.Timestamptz
	LockedUntil  pgtype.Timestamptz
}

type Invitation struct {
	ID         pgtype.UUID
	Email      string
	Role       string
	TokenHash  string
	InvitedBy  pgtype.UUID
	ExpiresAt  pgtype.Timestamptz
	AcceptedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type PasswordReset struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Permission struct {
	Key         string
	Description string
}

type PublicKey struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Label       string
	KeyType     string
	KeyBlob     string
	Fingerprint string
	CreatedAt   pgtype.Timestamptz
}

type ResourceGroup struct {
	ID          pgtype.UUID
	Name        string
	Description string
	CreatedAt   pgtype.Timestamptz
}

type Secret struct {
	ID           pgtype.UUID
	Label        string
	Url          pgtype.Text
	Username     pgtype.Text
	OtpRecipient pgtype.Text
	Ciphertext   []byte
	Nonce        []byte
	WrappedKey   []byte
	CreatedBy    pgtype.UUID
	UpdatedBy    pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type SecretAuditLog struct {
	ID         pgtype.UUID
	SecretID   pgtype.UUID
	SecretName string
	Action     string
	UserID     pgtype.UUID
	At         pgtype.Timestamptz
}

type SecretSet struct {
	ID        pgtype.UUID
	Name      string
	CreatedBy pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type SecretSetEntry struct {
	SetID      pgtype.UUID
	Key        string
	Ciphertext []byte
	Nonce      []byte
	WrappedKey []byte
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Session struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	TokenHash       string
	ClientPublicKey []byte
	CreatedAt       pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
	RevokedAt       pgtype.Timestamptz
}

type SetAuditLog struct {
	ID       pgtype.UUID
	SetName  string
	EntryKey pgtype.Text
	HostID   pgtype.UUID
	Action   string
	Actor    pgtype.UUID
	At       pgtype.Timestamptz
}

type SshAccessLog struct {
	ID          pgtype.UUID
	HostID      pgtype.UUID
	Hostname    string
	PublicKeyID pgtype.UUID
	Account     string
	Allowed     bool
	At          pgtype.Timestamptz
	Fingerprint string
}

type User struct {
	ID          pgtype.UUID
	Email       string
	Name        string
	DisplayName pgtype.Text
	Role        string
	Status      string
	CreatedAt   pgtype.Timestamptz
}
