// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EnrollmentToken struct {
	ID        pgtype.UUID
	TokenHash string
	Label     pgtype.Text
	Accounts  []string
	CreatedBy pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	HostID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type Grant struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Permission string
	TargetKind string
	TargetID   pgtype.UUID
	GrantedBy  pgtype.UUID
	CreatedAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

type GroupResource struct {
	GroupID      pgtype.UUID
	ResourceKind string
	ResourceID   pgtype.UUID
	AddedAt      pgtype.Timestamptz
}

type Host struct {
	ID          pgtype.UUID
	Name        string
	Hostname    string
	IdentityKey string
	Accounts    []string
	Status      string
	EnrolledAt  pgtype.Timestamptz
	LastSeenAt  pgtype.Timestamptz
}

type Identity struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Provider     string
	ExternalID   string
	PasswordHash pgtype.Text
	CreatedAt    pgtype.Timestamptz
	LastLoginAt  pgtype.Timestamptz
}

type Invitation struct {
	ID         pgtype.UUID
	Email      string
	Role       string
	TokenHash  string
	InvitedBy  pgtype.UUID
	ExpiresAt  pgtype.Timestamptz
	AcceptedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type Permission struct {
	Key         string
	Description string
}

type PublicKey struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Label       string
	KeyType     string
	KeyBlob     string
	Fingerprint string
	CreatedAt   pgtype.Timestamptz
}

type ResourceGroup struct {
	ID          pgtype.UUID
	Name        string
	Description string
	CreatedAt   pgtype.Timestamptz
}

type Secret struct {
	ID         pgtype.UUID
	Name       string
	Ciphertext []byte
	Nonce      []byte
	WrappedKey []byte
	CreatedBy  pgtype.UUID
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type SecretAuditLog struct {
	ID         pgtype.UUID
	SecretID   pgtype.UUID
	SecretName string
	Action     string
	UserID     pgtype.UUID
	At         pgtype.Timestamptz
}

type Session struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	TokenHash       string
	ClientPublicKey []byte
	CreatedAt       pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
	RevokedAt       pgtype.Timestamptz
}

type SshAccessLog struct {
	ID          pgtype.UUID
	HostID      pgtype.UUID
	PublicKeyID pgtype.UUID
	Account     string
	Allowed     bool
	At          pgtype.Timestamptz
}

type User struct {
	ID        pgtype.UUID
	Email     string
	Name      string
	Role      string
	Status    string
	CreatedAt pgtype.Timestamptz
}
