// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: permissions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listActiveAdmins = `-- name: ListActiveAdmins :many
select id as user_id, email, name, display_name, status from users
where role = 'admin' and status = 'active'
order by email
`

type ListActiveAdminsRow struct {
	UserID      pgtype.UUID
	Email       string
	Name        string
	DisplayName pgtype.Text
	Status      string
}

func (q *Queries) ListActiveAdmins(ctx context.Context) ([]ListActiveAdminsRow, error) {
	rows, err := q.db.Query(ctx, listActiveAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveAdminsRow{}
	for rows.Next() {
		var i ListActiveAdminsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.Name,
			&i.DisplayName,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGlobalPermissions = `-- name: ListGlobalPermissions :many
select key as permission, description
from permissions
where key in ('secret.add', 'group.create', 'set.add')
order by key
`

type ListGlobalPermissionsRow struct {
	Permission  string
	Description string
}

func (q *Queries) ListGlobalPermissions(ctx context.Context) ([]ListGlobalPermissionsRow, error) {
	rows, err := q.db.Query(ctx, listGlobalPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGlobalPermissionsRow{}
	for rows.Next() {
		var i ListGlobalPermissionsRow
		if err := rows.Scan(&i.Permission, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHostDirectAccess = `-- name: ListHostDirectAccess :many
select u.id as user_id, u.email, u.name, u.display_name, u.role, u.status, g.permission, g.created_at
from grants g
join users u on u.id = g.user_id
where g.revoked_at is null
  and g.permission = 'host.access'
  and g.target_kind = 'host' and g.target_id = $1
order by u.email
`

type ListHostDirectAccessRow struct {
	UserID      pgtype.UUID
	Email       string
	Name        string
	DisplayName pgtype.Text
	Role        string
	Status      string
	Permission  string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ListHostDirectAccess(ctx context.Context, hostID pgtype.UUID) ([]ListHostDirectAccessRow, error) {
	rows, err := q.db.Query(ctx, listHostDirectAccess, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHostDirectAccessRow{}
	for rows.Next() {
		var i ListHostDirectAccessRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.Name,
			&i.DisplayName,
			&i.Role,
			&i.Status,
			&i.Permission,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHostGroupAccess = `-- name: ListHostGroupAccess :many
select u.id as user_id, u.email, u.name, u.display_name, u.role, u.status, g.permission, g.created_at,
       rg.id as group_id, rg.name as group_name
from grants g
join users u on u.id = g.user_id
join resource_groups rg on rg.id = g.target_id
where g.revoked_at is null
  and g.permission = 'host.access'
  and g.target_kind = 'group'
  and rg.id in (
    select group_id from group_resources
    where resource_kind = 'host' and resource_id = $1
  )
order by rg.name, u.email
`

type ListHostGroupAccessRow struct {
	UserID      pgtype.UUID
	Email       string
	Name        string
	DisplayName pgtype.Text
	Role        string
	Status      string
	Permission  string
	CreatedAt   pgtype.Timestamptz
	GroupID     pgtype.UUID
	GroupName   string
}

func (q *Queries) ListHostGroupAccess(ctx context.Context, hostID pgtype.UUID) ([]ListHostGroupAccessRow, error) {
	rows, err := q.db.Query(ctx, listHostGroupAccess, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHostGroupAccessRow{}
	for rows.Next() {
		var i ListHostGroupAccessRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.Name,
			&i.DisplayName,
			&i.Role,
			&i.Status,
			&i.Permission,
			&i.CreatedAt,
			&i.GroupID,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecretDirectAccess = `-- name: ListSecretDirectAccess :many
select u.id as user_id, u.email, u.name, u.display_name, u.role, u.status, g.permission, g.created_at
from grants g
join users u on u.id = g.user_id
where g.revoked_at is null
  and g.target_kind = 'secret' and g.target_id = $1
order by u.email
`

type ListSecretDirectAccessRow struct {
	UserID      pgtype.UUID
	Email       string
	Name        string
	DisplayName pgtype.Text
	Role        string
	Status      string
	Permission  string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ListSecretDirectAccess(ctx context.Context, secretID pgtype.UUID) ([]ListSecretDirectAccessRow, error) {
	rows, err := q.db.Query(ctx, listSecretDirectAccess, secretID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSecretDirectAccessRow{}
	for rows.Next() {
		var i ListSecretDirectAccessRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.Name,
			&i.DisplayName,
			&i.Role,
			&i.Status,
			&i.Permission,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecretGroupAccess = `-- name: ListSecretGroupAccess :many
select u.id as user_id, u.email, u.name, u.display_name, u.role, u.status, g.permission, g.created_at,
       rg.id as group_id, rg.name as group_name
from grants g
join users u on u.id = g.user_id
join resource_groups rg on rg.id = g.target_id
where g.revoked_at is null
  and g.target_kind = 'group'
  and rg.id in (
    select group_id from group_resources
    where resource_kind = 'secret' and resource_id = $1
  )
order by rg.name, u.email
`

type ListSecretGroupAccessRow struct {
	UserID      pgtype.UUID
	Email       string
	Name        string
	DisplayName pgtype.Text
	Role        string
	Status      string
	Permission  string
	CreatedAt   pgtype.Timestamptz
	GroupID     pgtype.UUID
	GroupName   string
}

func (q *Queries) ListSecretGroupAccess(ctx context.Context, secretID pgtype.UUID) ([]ListSecretGroupAccessRow, error) {
	rows, err := q.db.Query(ctx, listSecretGroupAccess, secretID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSecretGroupAccessRow{}
	for rows.Next() {
		var i ListSecretGroupAccessRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.Name,
			&i.DisplayName,
			&i.Role,
			&i.Status,
			&i.Permission,
			&i.CreatedAt,
			&i.GroupID,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserGlobalPermissions = `-- name: ListUserGlobalPermissions :many
select g.id as grant_id, p.key as permission, p.description, g.created_at as granted_at
from grants g
join permissions p on p.key = g.permission
where g.user_id = $1
  and g.target_kind = 'global'
  and g.revoked_at is null
order by p.key
`

type ListUserGlobalPermissionsRow struct {
	GrantID     pgtype.UUID
	Permission  string
	Description string
	GrantedAt   pgtype.Timestamptz
}

func (q *Queries) ListUserGlobalPermissions(ctx context.Context, userID pgtype.UUID) ([]ListUserGlobalPermissionsRow, error) {
	rows, err := q.db.Query(ctx, listUserGlobalPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserGlobalPermissionsRow{}
	for rows.Next() {
		var i ListUserGlobalPermissionsRow
		if err := rows.Scan(
			&i.GrantID,
			&i.Permission,
			&i.Description,
			&i.GrantedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userHasGlobalPermission = `-- name: UserHasGlobalPermission :one
select exists (
  select 1 from grants
  where user_id = $1 and permission = $2
    and target_kind = 'global' and revoked_at is null
)
`

type UserHasGlobalPermissionParams struct {
	UserID     pgtype.UUID
	Permission string
}

func (q *Queries) UserHasGlobalPermission(ctx context.Context, arg UserHasGlobalPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, userHasGlobalPermission, arg.UserID, arg.Permission)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const userHasGroupPermission = `-- name: UserHasGroupPermission :one
select exists (
  select 1 from grants
  where user_id = $1 and permission = $2 and revoked_at is null
    and target_kind = 'group' and target_id = $3
)
`

type UserHasGroupPermissionParams struct {
	UserID     pgtype.UUID
	Permission string
	GroupID    pgtype.UUID
}

func (q *Queries) UserHasGroupPermission(ctx context.Context, arg UserHasGroupPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, userHasGroupPermission, arg.UserID, arg.Permission, arg.GroupID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const userHasHostPermission = `-- name: UserHasHostPermission :one
select exists (
  select 1 from grants g
  where g.user_id = $1 and g.permission = $2 and g.revoked_at is null
    and (
      (g.target_kind = 'host' and g.target_id = $3)
      or (g.target_kind = 'group' and g.target_id in (
        select group_id from group_resources
        where resource_kind = 'host' and resource_id = $3))
    )
)
`

type UserHasHostPermissionParams struct {
	UserID     pgtype.UUID
	Permission string
	HostID     pgtype.UUID
}

func (q *Queries) UserHasHostPermission(ctx context.Context, arg UserHasHostPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, userHasHostPermission, arg.UserID, arg.Permission, arg.HostID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const userHasSecretPermission = `-- name: UserHasSecretPermission :one
select exists (
  select 1 from grants g
  where g.user_id = $1 and g.permission = $2 and g.revoked_at is null
    and (
      (g.target_kind = 'secret' and g.target_id = $3)
      or (g.target_kind = 'group' and g.target_id in (
        select group_id from group_resources
        where resource_kind = 'secret' and resource_id = $3))
    )
)
`

type UserHasSecretPermissionParams struct {
	UserID     pgtype.UUID
	Permission string
	SecretID   pgtype.UUID
}

func (q *Queries) UserHasSecretPermission(ctx context.Context, arg UserHasSecretPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, userHasSecretPermission, arg.UserID, arg.Permission, arg.SecretID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const userHasSetPermission = `-- name: UserHasSetPermission :one
select exists (
  select 1 from grants g
  where g.user_id = $1 and g.permission = $2 and g.revoked_at is null
    and (
      (g.target_kind = 'set' and g.target_id = $3)
      or (g.target_kind = 'group' and g.target_id in (
        select group_id from group_resources
        where resource_kind = 'set' and resource_id = $3))
    )
)
`

type UserHasSetPermissionParams struct {
	UserID     pgtype.UUID
	Permission string
	SetID      pgtype.UUID
}

func (q *Queries) UserHasSetPermission(ctx context.Context, arg UserHasSetPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, userHasSetPermission, arg.UserID, arg.Permission, arg.SetID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
