// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: permissions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const userHasGlobalPermission = `-- name: UserHasGlobalPermission :one
select exists (
  select 1 from grants
  where user_id = $1 and permission = $2
    and target_kind = 'global' and revoked_at is null
)
`

type UserHasGlobalPermissionParams struct {
	UserID     pgtype.UUID
	Permission string
}

func (q *Queries) UserHasGlobalPermission(ctx context.Context, arg UserHasGlobalPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, userHasGlobalPermission, arg.UserID, arg.Permission)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const userHasSecretPermission = `-- name: UserHasSecretPermission :one
select exists (
  select 1 from grants g
  where g.user_id = $1 and g.permission = $2 and g.revoked_at is null
    and (
      (g.target_kind = 'secret' and g.target_id = $3)
      or (g.target_kind = 'group' and g.target_id in (
        select group_id from group_resources
        where resource_kind = 'secret' and resource_id = $3))
    )
)
`

type UserHasSecretPermissionParams struct {
	UserID     pgtype.UUID
	Permission string
	SecretID   pgtype.UUID
}

func (q *Queries) UserHasSecretPermission(ctx context.Context, arg UserHasSecretPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, userHasSecretPermission, arg.UserID, arg.Permission, arg.SecretID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
