// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: public_keys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPublicKey = `-- name: CreatePublicKey :one
insert into public_keys (user_id, label, key_type, key_blob, fingerprint)
values ($1, $2, $3, $4, $5)
returning id, user_id, label, key_type, key_blob, fingerprint, created_at
`

type CreatePublicKeyParams struct {
	UserID      pgtype.UUID
	Label       string
	KeyType     string
	KeyBlob     string
	Fingerprint string
}

func (q *Queries) CreatePublicKey(ctx context.Context, arg CreatePublicKeyParams) (PublicKey, error) {
	row := q.db.QueryRow(ctx, createPublicKey,
		arg.UserID,
		arg.Label,
		arg.KeyType,
		arg.KeyBlob,
		arg.Fingerprint,
	)
	var i PublicKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.KeyType,
		&i.KeyBlob,
		&i.Fingerprint,
		&i.CreatedAt,
	)
	return i, err
}

const deletePublicKey = `-- name: DeletePublicKey :execrows
delete from public_keys where id = $1 and user_id = $2
`

type DeletePublicKeyParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeletePublicKey(ctx context.Context, arg DeletePublicKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePublicKey, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listUserPublicKeys = `-- name: ListUserPublicKeys :many
select id, user_id, label, key_type, key_blob, fingerprint, created_at from public_keys where user_id = $1 order by created_at
`

func (q *Queries) ListUserPublicKeys(ctx context.Context, userID pgtype.UUID) ([]PublicKey, error) {
	rows, err := q.db.Query(ctx, listUserPublicKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PublicKey{}
	for rows.Next() {
		var i PublicKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Label,
			&i.KeyType,
			&i.KeyBlob,
			&i.Fingerprint,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
