// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: secret_sets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bindSet = `-- name: BindSet :exec
insert into host_set_bindings (host_id, set_id, as_user, granted_by)
values ($1, $2, $3, $4)
on conflict (host_id, set_id) do update
  set as_user = excluded.as_user, granted_by = excluded.granted_by, revoked_at = null
`

type BindSetParams struct {
	HostID    pgtype.UUID
	SetID     pgtype.UUID
	AsUser    pgtype.Text
	GrantedBy pgtype.UUID
}

func (q *Queries) BindSet(ctx context.Context, arg BindSetParams) error {
	_, err := q.db.Exec(ctx, bindSet,
		arg.HostID,
		arg.SetID,
		arg.AsUser,
		arg.GrantedBy,
	)
	return err
}

const createSet = `-- name: CreateSet :one
insert into secret_sets (name, created_by) values ($1, $2) returning id, name, created_by, created_at, updated_at
`

type CreateSetParams struct {
	Name      string
	CreatedBy pgtype.UUID
}

func (q *Queries) CreateSet(ctx context.Context, arg CreateSetParams) (SecretSet, error) {
	row := q.db.QueryRow(ctx, createSet, arg.Name, arg.CreatedBy)
	var i SecretSet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSetEntry = `-- name: CreateSetEntry :exec
insert into secret_set_entries (set_id, key, ciphertext, nonce, wrapped_key)
values ($1, $2, $3, $4, $5)
`

type CreateSetEntryParams struct {
	SetID      pgtype.UUID
	Key        string
	Ciphertext []byte
	Nonce      []byte
	WrappedKey []byte
}

func (q *Queries) CreateSetEntry(ctx context.Context, arg CreateSetEntryParams) error {
	_, err := q.db.Exec(ctx, createSetEntry,
		arg.SetID,
		arg.Key,
		arg.Ciphertext,
		arg.Nonce,
		arg.WrappedKey,
	)
	return err
}

const deleteSet = `-- name: DeleteSet :execrows
delete from secret_sets where id = $1
`

func (q *Queries) DeleteSet(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSet, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSetEntries = `-- name: DeleteSetEntries :exec
delete from secret_set_entries where set_id = $1
`

func (q *Queries) DeleteSetEntries(ctx context.Context, setID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSetEntries, setID)
	return err
}

const deleteSetEntry = `-- name: DeleteSetEntry :execrows
delete from secret_set_entries where set_id = $1 and key = $2
`

type DeleteSetEntryParams struct {
	SetID pgtype.UUID
	Key   string
}

func (q *Queries) DeleteSetEntry(ctx context.Context, arg DeleteSetEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSetEntry, arg.SetID, arg.Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSet = `-- name: GetSet :one
select id, name, created_by, created_at, updated_at from secret_sets where id = $1
`

func (q *Queries) GetSet(ctx context.Context, id pgtype.UUID) (SecretSet, error) {
	row := q.db.QueryRow(ctx, getSet, id)
	var i SecretSet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSetByName = `-- name: GetSetByName :one
select id, name, created_by, created_at, updated_at from secret_sets where name = $1
`

func (q *Queries) GetSetByName(ctx context.Context, name string) (SecretSet, error) {
	row := q.db.QueryRow(ctx, getSetByName, name)
	var i SecretSet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSetEntries = `-- name: GetSetEntries :many
select key, ciphertext, nonce, wrapped_key from secret_set_entries where set_id = $1 order by key
`

type GetSetEntriesRow struct {
	Key        string
	Ciphertext []byte
	Nonce      []byte
	WrappedKey []byte
}

func (q *Queries) GetSetEntries(ctx context.Context, setID pgtype.UUID) ([]GetSetEntriesRow, error) {
	rows, err := q.db.Query(ctx, getSetEntries, setID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSetEntriesRow{}
	for rows.Next() {
		var i GetSetEntriesRow
		if err := rows.Scan(
			&i.Key,
			&i.Ciphertext,
			&i.Nonce,
			&i.WrappedKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hostsForSet = `-- name: HostsForSet :many
select host_id from host_set_bindings where set_id = $1 and revoked_at is null
`

func (q *Queries) HostsForSet(ctx context.Context, setID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, hostsForSet, setID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var host_id pgtype.UUID
		if err := rows.Scan(&host_id); err != nil {
			return nil, err
		}
		items = append(items, host_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSetAudit = `-- name: InsertSetAudit :exec
insert into set_audit_logs (set_id, set_name, entry_key, host_id, action, actor)
values ($1, $2, $3, $4, $5, $6)
`

type InsertSetAuditParams struct {
	SetID    pgtype.UUID
	SetName  string
	EntryKey pgtype.Text
	HostID   pgtype.UUID
	Action   string
	Actor    pgtype.UUID
}

func (q *Queries) InsertSetAudit(ctx context.Context, arg InsertSetAuditParams) error {
	_, err := q.db.Exec(ctx, insertSetAudit,
		arg.SetID,
		arg.SetName,
		arg.EntryKey,
		arg.HostID,
		arg.Action,
		arg.Actor,
	)
	return err
}

const listHostsForSet = `-- name: ListHostsForSet :many
select h.id, h.name, h.hostname, h.accounts, h.status, h.agent_version, h.desired_version,
       h.enrolled_at, h.last_seen_at, hsb.as_user, hsb.created_at as bound_at
from host_set_bindings hsb
join hosts h on h.id = hsb.host_id
where hsb.set_id = $1 and hsb.revoked_at is null
order by h.name
`

type ListHostsForSetRow struct {
	ID             pgtype.UUID
	Name           string
	Hostname       string
	Accounts       []string
	Status         string
	AgentVersion   string
	DesiredVersion string
	EnrolledAt     pgtype.Timestamptz
	LastSeenAt     pgtype.Timestamptz
	AsUser         pgtype.Text
	BoundAt        pgtype.Timestamptz
}

func (q *Queries) ListHostsForSet(ctx context.Context, setID pgtype.UUID) ([]ListHostsForSetRow, error) {
	rows, err := q.db.Query(ctx, listHostsForSet, setID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHostsForSetRow{}
	for rows.Next() {
		var i ListHostsForSetRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Hostname,
			&i.Accounts,
			&i.Status,
			&i.AgentVersion,
			&i.DesiredVersion,
			&i.EnrolledAt,
			&i.LastSeenAt,
			&i.AsUser,
			&i.BoundAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadableSets = `-- name: ListReadableSets :many
select distinct ss.id, ss.name, ss.created_at, ss.updated_at, coalesce(k.key_count, 0)::bigint as key_count
from secret_sets ss
join grants g on g.permission = 'set.read' and g.revoked_at is null
  and g.target_kind = 'set' and g.target_id = ss.id
left join (
  select set_id, count(*) as key_count
  from secret_set_entries
  group by set_id
) k on k.set_id = ss.id
where g.user_id = $1
order by ss.name
`

type ListReadableSetsRow struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	KeyCount  int64
}

func (q *Queries) ListReadableSets(ctx context.Context, userID pgtype.UUID) ([]ListReadableSetsRow, error) {
	rows, err := q.db.Query(ctx, listReadableSets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReadableSetsRow{}
	for rows.Next() {
		var i ListReadableSetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.KeyCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSetAudit = `-- name: ListSetAudit :many
select a.action, a.set_name, a.entry_key, a.host_id, a.actor, u.email as actor_email,
       u.name as actor_name, u.display_name as actor_display_name, a.at
from set_audit_logs a
left join users u on u.id = a.actor
where a.set_id = $1 or (a.set_id is null and a.set_name = $2)
order by a.at desc
limit 100
`

type ListSetAuditParams struct {
	SetID   pgtype.UUID
	SetName string
}

type ListSetAuditRow struct {
	Action           string
	SetName          string
	EntryKey         pgtype.Text
	HostID           pgtype.UUID
	Actor            pgtype.UUID
	ActorEmail       pgtype.Text
	ActorName        pgtype.Text
	ActorDisplayName pgtype.Text
	At               pgtype.Timestamptz
}

func (q *Queries) ListSetAudit(ctx context.Context, arg ListSetAuditParams) ([]ListSetAuditRow, error) {
	rows, err := q.db.Query(ctx, listSetAudit, arg.SetID, arg.SetName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSetAuditRow{}
	for rows.Next() {
		var i ListSetAuditRow
		if err := rows.Scan(
			&i.Action,
			&i.SetName,
			&i.EntryKey,
			&i.HostID,
			&i.Actor,
			&i.ActorEmail,
			&i.ActorName,
			&i.ActorDisplayName,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSetKeys = `-- name: ListSetKeys :many
select key from secret_set_entries where set_id = $1 order by key
`

func (q *Queries) ListSetKeys(ctx context.Context, setID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listSetKeys, setID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSets = `-- name: ListSets :many
select ss.id, ss.name, ss.created_at, ss.updated_at, coalesce(k.key_count, 0)::bigint as key_count
from secret_sets ss
left join (
  select set_id, count(*) as key_count
  from secret_set_entries
  group by set_id
) k on k.set_id = ss.id
order by ss.name
`

type ListSetsRow struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	KeyCount  int64
}

func (q *Queries) ListSets(ctx context.Context) ([]ListSetsRow, error) {
	rows, err := q.db.Query(ctx, listSets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSetsRow{}
	for rows.Next() {
		var i ListSetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.KeyCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setsForHost = `-- name: SetsForHost :many
select ss.id, ss.name, ss.updated_at, hsb.as_user
from host_set_bindings hsb
join secret_sets ss on ss.id = hsb.set_id
where hsb.host_id = $1 and hsb.revoked_at is null
order by ss.name
`

type SetsForHostRow struct {
	ID        pgtype.UUID
	Name      string
	UpdatedAt pgtype.Timestamptz
	AsUser    pgtype.Text
}

func (q *Queries) SetsForHost(ctx context.Context, hostID pgtype.UUID) ([]SetsForHostRow, error) {
	rows, err := q.db.Query(ctx, setsForHost, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SetsForHostRow{}
	for rows.Next() {
		var i SetsForHostRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UpdatedAt,
			&i.AsUser,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchSet = `-- name: TouchSet :exec
update secret_sets set updated_at = now() where id = $1
`

func (q *Queries) TouchSet(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchSet, id)
	return err
}

const unbindSet = `-- name: UnbindSet :execrows
delete from host_set_bindings where host_id = $1 and set_id = $2
`

type UnbindSetParams struct {
	HostID pgtype.UUID
	SetID  pgtype.UUID
}

func (q *Queries) UnbindSet(ctx context.Context, arg UnbindSetParams) (int64, error) {
	result, err := q.db.Exec(ctx, unbindSet, arg.HostID, arg.SetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSetName = `-- name: UpdateSetName :one
update secret_sets set name = $2, updated_at = now() where id = $1 returning id, name, created_by, created_at, updated_at
`

type UpdateSetNameParams struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) UpdateSetName(ctx context.Context, arg UpdateSetNameParams) (SecretSet, error) {
	row := q.db.QueryRow(ctx, updateSetName, arg.ID, arg.Name)
	var i SecretSet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSetEntry = `-- name: UpsertSetEntry :exec
insert into secret_set_entries (set_id, key, ciphertext, nonce, wrapped_key)
values ($1, $2, $3, $4, $5)
on conflict (set_id, key) do update
  set ciphertext = excluded.ciphertext, nonce = excluded.nonce,
      wrapped_key = excluded.wrapped_key, updated_at = now()
`

type UpsertSetEntryParams struct {
	SetID      pgtype.UUID
	Key        string
	Ciphertext []byte
	Nonce      []byte
	WrappedKey []byte
}

func (q *Queries) UpsertSetEntry(ctx context.Context, arg UpsertSetEntryParams) error {
	_, err := q.db.Exec(ctx, upsertSetEntry,
		arg.SetID,
		arg.Key,
		arg.Ciphertext,
		arg.Nonce,
		arg.WrappedKey,
	)
	return err
}
