// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: secret_sets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSet = `-- name: CreateSet :one
insert into secret_sets (name, created_by) values ($1, $2) returning id, name, created_by, created_at, updated_at
`

type CreateSetParams struct {
	Name      string
	CreatedBy pgtype.UUID
}

func (q *Queries) CreateSet(ctx context.Context, arg CreateSetParams) (SecretSet, error) {
	row := q.db.QueryRow(ctx, createSet, arg.Name, arg.CreatedBy)
	var i SecretSet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSetEntry = `-- name: CreateSetEntry :exec
insert into secret_set_entries (set_id, key, ciphertext, nonce, wrapped_key)
values ($1, $2, $3, $4, $5)
`

type CreateSetEntryParams struct {
	SetID      pgtype.UUID
	Key        string
	Ciphertext []byte
	Nonce      []byte
	WrappedKey []byte
}

func (q *Queries) CreateSetEntry(ctx context.Context, arg CreateSetEntryParams) error {
	_, err := q.db.Exec(ctx, createSetEntry,
		arg.SetID,
		arg.Key,
		arg.Ciphertext,
		arg.Nonce,
		arg.WrappedKey,
	)
	return err
}

const deleteSet = `-- name: DeleteSet :execrows
delete from secret_sets where id = $1
`

func (q *Queries) DeleteSet(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSet, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSetEntries = `-- name: DeleteSetEntries :exec
delete from secret_set_entries where set_id = $1
`

func (q *Queries) DeleteSetEntries(ctx context.Context, setID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSetEntries, setID)
	return err
}

const getSet = `-- name: GetSet :one
select id, name, created_by, created_at, updated_at from secret_sets where id = $1
`

func (q *Queries) GetSet(ctx context.Context, id pgtype.UUID) (SecretSet, error) {
	row := q.db.QueryRow(ctx, getSet, id)
	var i SecretSet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSetAudit = `-- name: InsertSetAudit :exec
insert into set_audit_logs (set_name, entry_key, host_id, action, actor)
values ($1, $2, $3, $4, $5)
`

type InsertSetAuditParams struct {
	SetName  string
	EntryKey pgtype.Text
	HostID   pgtype.UUID
	Action   string
	Actor    pgtype.UUID
}

func (q *Queries) InsertSetAudit(ctx context.Context, arg InsertSetAuditParams) error {
	_, err := q.db.Exec(ctx, insertSetAudit,
		arg.SetName,
		arg.EntryKey,
		arg.HostID,
		arg.Action,
		arg.Actor,
	)
	return err
}

const listReadableSets = `-- name: ListReadableSets :many
select distinct ss.id, ss.name, ss.created_at, ss.updated_at
from secret_sets ss
join grants g on g.permission = 'set.read' and g.revoked_at is null
  and g.target_kind = 'set' and g.target_id = ss.id
where g.user_id = $1
order by ss.name
`

type ListReadableSetsRow struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListReadableSets(ctx context.Context, userID pgtype.UUID) ([]ListReadableSetsRow, error) {
	rows, err := q.db.Query(ctx, listReadableSets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReadableSetsRow{}
	for rows.Next() {
		var i ListReadableSetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSetKeys = `-- name: ListSetKeys :many
select key from secret_set_entries where set_id = $1 order by key
`

func (q *Queries) ListSetKeys(ctx context.Context, setID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listSetKeys, setID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSets = `-- name: ListSets :many
select id, name, created_at, updated_at from secret_sets order by name
`

type ListSetsRow struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListSets(ctx context.Context) ([]ListSetsRow, error) {
	rows, err := q.db.Query(ctx, listSets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSetsRow{}
	for rows.Next() {
		var i ListSetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchSet = `-- name: TouchSet :exec
update secret_sets set updated_at = now() where id = $1
`

func (q *Queries) TouchSet(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchSet, id)
	return err
}
