// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: secrets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSecret = `-- name: CreateSecret :one
insert into secrets (label, url, username, otp_recipient, ciphertext, nonce, wrapped_key, created_by, updated_by)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
returning id, label, url, username, otp_recipient, ciphertext, nonce, wrapped_key, created_by, updated_by, created_at, updated_at
`

type CreateSecretParams struct {
	Label        string
	Url          pgtype.Text
	Username     pgtype.Text
	OtpRecipient pgtype.Text
	Ciphertext   []byte
	Nonce        []byte
	WrappedKey   []byte
	CreatedBy    pgtype.UUID
	UpdatedBy    pgtype.UUID
}

func (q *Queries) CreateSecret(ctx context.Context, arg CreateSecretParams) (Secret, error) {
	row := q.db.QueryRow(ctx, createSecret,
		arg.Label,
		arg.Url,
		arg.Username,
		arg.OtpRecipient,
		arg.Ciphertext,
		arg.Nonce,
		arg.WrappedKey,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Url,
		&i.Username,
		&i.OtpRecipient,
		&i.Ciphertext,
		&i.Nonce,
		&i.WrappedKey,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSecret = `-- name: DeleteSecret :exec
delete from secrets where id = $1
`

func (q *Queries) DeleteSecret(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSecret, id)
	return err
}

const getSecret = `-- name: GetSecret :one
select s.id, s.label, s.url, s.username, s.otp_recipient, s.ciphertext, s.nonce, s.wrapped_key, s.created_by, s.updated_by, s.created_at, s.updated_at,
       cu.name as created_by_name, cu.display_name as created_by_display_name, cu.email as created_by_email,
       uu.name as updated_by_name, uu.display_name as updated_by_display_name, uu.email as updated_by_email
from secrets s
left join users cu on cu.id = s.created_by
left join users uu on uu.id = s.updated_by
where s.id = $1
`

type GetSecretRow struct {
	ID                   pgtype.UUID
	Label                string
	Url                  pgtype.Text
	Username             pgtype.Text
	OtpRecipient         pgtype.Text
	Ciphertext           []byte
	Nonce                []byte
	WrappedKey           []byte
	CreatedBy            pgtype.UUID
	UpdatedBy            pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	CreatedByName        pgtype.Text
	CreatedByDisplayName pgtype.Text
	CreatedByEmail       pgtype.Text
	UpdatedByName        pgtype.Text
	UpdatedByDisplayName pgtype.Text
	UpdatedByEmail       pgtype.Text
}

func (q *Queries) GetSecret(ctx context.Context, id pgtype.UUID) (GetSecretRow, error) {
	row := q.db.QueryRow(ctx, getSecret, id)
	var i GetSecretRow
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Url,
		&i.Username,
		&i.OtpRecipient,
		&i.Ciphertext,
		&i.Nonce,
		&i.WrappedKey,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByName,
		&i.CreatedByDisplayName,
		&i.CreatedByEmail,
		&i.UpdatedByName,
		&i.UpdatedByDisplayName,
		&i.UpdatedByEmail,
	)
	return i, err
}

const insertSecretAudit = `-- name: InsertSecretAudit :exec
insert into secret_audit_logs (secret_id, secret_name, action, user_id)
values ($1, $2, $3, $4)
`

type InsertSecretAuditParams struct {
	SecretID   pgtype.UUID
	SecretName string
	Action     string
	UserID     pgtype.UUID
}

func (q *Queries) InsertSecretAudit(ctx context.Context, arg InsertSecretAuditParams) error {
	_, err := q.db.Exec(ctx, insertSecretAudit,
		arg.SecretID,
		arg.SecretName,
		arg.Action,
		arg.UserID,
	)
	return err
}

const listAllSecretAudit = `-- name: ListAllSecretAudit :many
select a.id, a.action, a.at, a.secret_id, a.secret_name, u.id as user_id, u.email as user_email
from secret_audit_logs a
left join users u on u.id = a.user_id
order by a.at desc
limit $1
`

type ListAllSecretAuditRow struct {
	ID         pgtype.UUID
	Action     string
	At         pgtype.Timestamptz
	SecretID   pgtype.UUID
	SecretName string
	UserID     pgtype.UUID
	UserEmail  pgtype.Text
}

func (q *Queries) ListAllSecretAudit(ctx context.Context, limit int32) ([]ListAllSecretAuditRow, error) {
	rows, err := q.db.Query(ctx, listAllSecretAudit, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllSecretAuditRow{}
	for rows.Next() {
		var i ListAllSecretAuditRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.At,
			&i.SecretID,
			&i.SecretName,
			&i.UserID,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllSecrets = `-- name: ListAllSecrets :many
select s.id, s.label, s.url, s.username, s.otp_recipient, s.created_at, s.updated_at,
       s.created_by, cu.name as created_by_name, cu.display_name as created_by_display_name, cu.email as created_by_email,
       s.updated_by, uu.name as updated_by_name, uu.display_name as updated_by_display_name, uu.email as updated_by_email
from secrets s
left join users cu on cu.id = s.created_by
left join users uu on uu.id = s.updated_by
order by s.label
`

type ListAllSecretsRow struct {
	ID                   pgtype.UUID
	Label                string
	Url                  pgtype.Text
	Username             pgtype.Text
	OtpRecipient         pgtype.Text
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	CreatedBy            pgtype.UUID
	CreatedByName        pgtype.Text
	CreatedByDisplayName pgtype.Text
	CreatedByEmail       pgtype.Text
	UpdatedBy            pgtype.UUID
	UpdatedByName        pgtype.Text
	UpdatedByDisplayName pgtype.Text
	UpdatedByEmail       pgtype.Text
}

func (q *Queries) ListAllSecrets(ctx context.Context) ([]ListAllSecretsRow, error) {
	rows, err := q.db.Query(ctx, listAllSecrets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllSecretsRow{}
	for rows.Next() {
		var i ListAllSecretsRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Url,
			&i.Username,
			&i.OtpRecipient,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.CreatedByName,
			&i.CreatedByDisplayName,
			&i.CreatedByEmail,
			&i.UpdatedBy,
			&i.UpdatedByName,
			&i.UpdatedByDisplayName,
			&i.UpdatedByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadableSecrets = `-- name: ListReadableSecrets :many
select distinct s.id, s.label, s.url, s.username, s.otp_recipient, s.created_at, s.updated_at,
       s.created_by, cu.name as created_by_name, cu.display_name as created_by_display_name, cu.email as created_by_email,
       s.updated_by, uu.name as updated_by_name, uu.display_name as updated_by_display_name, uu.email as updated_by_email
from secrets s
join grants g on g.permission = 'secret.read' and g.revoked_at is null
  and (
    (g.target_kind = 'secret' and g.target_id = s.id)
    or (g.target_kind = 'group' and g.target_id in (
      select group_id from group_resources where resource_kind = 'secret' and resource_id = s.id))
  )
left join users cu on cu.id = s.created_by
left join users uu on uu.id = s.updated_by
where g.user_id = $1
order by s.label
`

type ListReadableSecretsRow struct {
	ID                   pgtype.UUID
	Label                string
	Url                  pgtype.Text
	Username             pgtype.Text
	OtpRecipient         pgtype.Text
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	CreatedBy            pgtype.UUID
	CreatedByName        pgtype.Text
	CreatedByDisplayName pgtype.Text
	CreatedByEmail       pgtype.Text
	UpdatedBy            pgtype.UUID
	UpdatedByName        pgtype.Text
	UpdatedByDisplayName pgtype.Text
	UpdatedByEmail       pgtype.Text
}

func (q *Queries) ListReadableSecrets(ctx context.Context, userID pgtype.UUID) ([]ListReadableSecretsRow, error) {
	rows, err := q.db.Query(ctx, listReadableSecrets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReadableSecretsRow{}
	for rows.Next() {
		var i ListReadableSecretsRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Url,
			&i.Username,
			&i.OtpRecipient,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.CreatedByName,
			&i.CreatedByDisplayName,
			&i.CreatedByEmail,
			&i.UpdatedBy,
			&i.UpdatedByName,
			&i.UpdatedByDisplayName,
			&i.UpdatedByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecretAudit = `-- name: ListSecretAudit :many
select a.id, a.action, a.at, a.secret_id, a.secret_name, u.id as user_id, u.email as user_email
from secret_audit_logs a
left join users u on u.id = a.user_id
where a.secret_id = $1
order by a.at desc
`

type ListSecretAuditRow struct {
	ID         pgtype.UUID
	Action     string
	At         pgtype.Timestamptz
	SecretID   pgtype.UUID
	SecretName string
	UserID     pgtype.UUID
	UserEmail  pgtype.Text
}

func (q *Queries) ListSecretAudit(ctx context.Context, secretID pgtype.UUID) ([]ListSecretAuditRow, error) {
	rows, err := q.db.Query(ctx, listSecretAudit, secretID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSecretAuditRow{}
	for rows.Next() {
		var i ListSecretAuditRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.At,
			&i.SecretID,
			&i.SecretName,
			&i.UserID,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSecret = `-- name: UpdateSecret :one
update secrets set label = $2, url = $3, username = $4, otp_recipient = $5,
  ciphertext = $6, nonce = $7, wrapped_key = $8, updated_by = $9, updated_at = now()
where id = $1
returning id, label, url, username, otp_recipient, ciphertext, nonce, wrapped_key, created_by, updated_by, created_at, updated_at
`

type UpdateSecretParams struct {
	ID           pgtype.UUID
	Label        string
	Url          pgtype.Text
	Username     pgtype.Text
	OtpRecipient pgtype.Text
	Ciphertext   []byte
	Nonce        []byte
	WrappedKey   []byte
	UpdatedBy    pgtype.UUID
}

func (q *Queries) UpdateSecret(ctx context.Context, arg UpdateSecretParams) (Secret, error) {
	row := q.db.QueryRow(ctx, updateSecret,
		arg.ID,
		arg.Label,
		arg.Url,
		arg.Username,
		arg.OtpRecipient,
		arg.Ciphertext,
		arg.Nonce,
		arg.WrappedKey,
		arg.UpdatedBy,
	)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Url,
		&i.Username,
		&i.OtpRecipient,
		&i.Ciphertext,
		&i.Nonce,
		&i.WrappedKey,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
