// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: secrets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSecret = `-- name: CreateSecret :one
insert into secrets (name, ciphertext, nonce, wrapped_key, created_by)
values ($1, $2, $3, $4, $5)
returning id, name, ciphertext, nonce, wrapped_key, created_by, created_at, updated_at
`

type CreateSecretParams struct {
	Name       string
	Ciphertext []byte
	Nonce      []byte
	WrappedKey []byte
	CreatedBy  pgtype.UUID
}

func (q *Queries) CreateSecret(ctx context.Context, arg CreateSecretParams) (Secret, error) {
	row := q.db.QueryRow(ctx, createSecret,
		arg.Name,
		arg.Ciphertext,
		arg.Nonce,
		arg.WrappedKey,
		arg.CreatedBy,
	)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ciphertext,
		&i.Nonce,
		&i.WrappedKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSecret = `-- name: DeleteSecret :exec
delete from secrets where id = $1
`

func (q *Queries) DeleteSecret(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSecret, id)
	return err
}

const getSecret = `-- name: GetSecret :one
select id, name, ciphertext, nonce, wrapped_key, created_by, created_at, updated_at from secrets where id = $1
`

func (q *Queries) GetSecret(ctx context.Context, id pgtype.UUID) (Secret, error) {
	row := q.db.QueryRow(ctx, getSecret, id)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ciphertext,
		&i.Nonce,
		&i.WrappedKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSecretAudit = `-- name: InsertSecretAudit :exec
insert into secret_audit_logs (secret_id, secret_name, action, user_id)
values ($1, $2, $3, $4)
`

type InsertSecretAuditParams struct {
	SecretID   pgtype.UUID
	SecretName string
	Action     string
	UserID     pgtype.UUID
}

func (q *Queries) InsertSecretAudit(ctx context.Context, arg InsertSecretAuditParams) error {
	_, err := q.db.Exec(ctx, insertSecretAudit,
		arg.SecretID,
		arg.SecretName,
		arg.Action,
		arg.UserID,
	)
	return err
}

const listAllSecretAudit = `-- name: ListAllSecretAudit :many
select a.id, a.action, a.at, a.secret_id, a.secret_name, u.id as user_id, u.email as user_email
from secret_audit_logs a
left join users u on u.id = a.user_id
order by a.at desc
limit $1
`

type ListAllSecretAuditRow struct {
	ID         pgtype.UUID
	Action     string
	At         pgtype.Timestamptz
	SecretID   pgtype.UUID
	SecretName string
	UserID     pgtype.UUID
	UserEmail  pgtype.Text
}

func (q *Queries) ListAllSecretAudit(ctx context.Context, limit int32) ([]ListAllSecretAuditRow, error) {
	rows, err := q.db.Query(ctx, listAllSecretAudit, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllSecretAuditRow{}
	for rows.Next() {
		var i ListAllSecretAuditRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.At,
			&i.SecretID,
			&i.SecretName,
			&i.UserID,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllSecrets = `-- name: ListAllSecrets :many
select id, name, created_at, updated_at from secrets order by name
`

type ListAllSecretsRow struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListAllSecrets(ctx context.Context) ([]ListAllSecretsRow, error) {
	rows, err := q.db.Query(ctx, listAllSecrets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllSecretsRow{}
	for rows.Next() {
		var i ListAllSecretsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadableSecrets = `-- name: ListReadableSecrets :many
select distinct s.id, s.name, s.created_at, s.updated_at
from secrets s
join grants g on g.permission = 'secret.read' and g.revoked_at is null
  and (
    (g.target_kind = 'secret' and g.target_id = s.id)
    or (g.target_kind = 'group' and g.target_id in (
      select group_id from group_resources
      where resource_kind = 'secret' and resource_id = s.id))
  )
where g.user_id = $1
order by s.name
`

type ListReadableSecretsRow struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListReadableSecrets(ctx context.Context, userID pgtype.UUID) ([]ListReadableSecretsRow, error) {
	rows, err := q.db.Query(ctx, listReadableSecrets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReadableSecretsRow{}
	for rows.Next() {
		var i ListReadableSecretsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecretAudit = `-- name: ListSecretAudit :many
select a.id, a.action, a.at, a.secret_id, a.secret_name, u.id as user_id, u.email as user_email
from secret_audit_logs a
left join users u on u.id = a.user_id
where a.secret_id = $1
order by a.at desc
`

type ListSecretAuditRow struct {
	ID         pgtype.UUID
	Action     string
	At         pgtype.Timestamptz
	SecretID   pgtype.UUID
	SecretName string
	UserID     pgtype.UUID
	UserEmail  pgtype.Text
}

func (q *Queries) ListSecretAudit(ctx context.Context, secretID pgtype.UUID) ([]ListSecretAuditRow, error) {
	rows, err := q.db.Query(ctx, listSecretAudit, secretID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSecretAuditRow{}
	for rows.Next() {
		var i ListSecretAuditRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.At,
			&i.SecretID,
			&i.SecretName,
			&i.UserID,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSecret = `-- name: UpdateSecret :one
update secrets set ciphertext = $2, nonce = $3, wrapped_key = $4, updated_at = now()
where id = $1
returning id, name, ciphertext, nonce, wrapped_key, created_by, created_at, updated_at
`

type UpdateSecretParams struct {
	ID         pgtype.UUID
	Ciphertext []byte
	Nonce      []byte
	WrappedKey []byte
}

func (q *Queries) UpdateSecret(ctx context.Context, arg UpdateSecretParams) (Secret, error) {
	row := q.db.QueryRow(ctx, updateSecret,
		arg.ID,
		arg.Ciphertext,
		arg.Nonce,
		arg.WrappedKey,
	)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ciphertext,
		&i.Nonce,
		&i.WrappedKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
