// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
insert into sessions (user_id, token_hash, client_public_key, expires_at)
values ($1, $2, $3, $4)
returning id, user_id, token_hash, client_public_key, created_at, expires_at, revoked_at
`

type CreateSessionParams struct {
	UserID          pgtype.UUID
	TokenHash       string
	ClientPublicKey []byte
	ExpiresAt       pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.ClientPublicKey,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ClientPublicKey,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
select id, user_id, token_hash, client_public_key, created_at, expires_at, revoked_at from sessions
where token_hash = $1 and revoked_at is null and expires_at > now()
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ClientPublicKey,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
update sessions set revoked_at = now() where user_id = $1 and revoked_at is null
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
update sessions set revoked_at = now() where id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const rotateSessionToken = `-- name: RotateSessionToken :exec
update sessions set token_hash = $2 where id = $1
`

type RotateSessionTokenParams struct {
	ID        pgtype.UUID
	TokenHash string
}

func (q *Queries) RotateSessionToken(ctx context.Context, arg RotateSessionTokenParams) error {
	_, err := q.db.Exec(ctx, rotateSessionToken, arg.ID, arg.TokenHash)
	return err
}

const updateSessionClientKey = `-- name: UpdateSessionClientKey :exec
update sessions set client_public_key = $2 where id = $1
`

type UpdateSessionClientKeyParams struct {
	ID              pgtype.UUID
	ClientPublicKey []byte
}

func (q *Queries) UpdateSessionClientKey(ctx context.Context, arg UpdateSessionClientKeyParams) error {
	_, err := q.db.Exec(ctx, updateSessionClientKey, arg.ID, arg.ClientPublicKey)
	return err
}
