// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: snapshot.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const hostAccessKeys = `-- name: HostAccessKeys :many
select distinct pk.user_id, pk.key_type, pk.key_blob, pk.fingerprint
from grants g
join users u on u.id = g.user_id and u.status = 'active'
join public_keys pk on pk.user_id = g.user_id
where g.permission = 'host.access'
  and g.revoked_at is null
  and (
    (g.target_kind = 'host' and g.target_id = $1)
    or (g.target_kind = 'group' and g.target_id in (
      select group_id from group_resources
      where resource_kind = 'host' and resource_id = $1
    ))
  )
`

type HostAccessKeysRow struct {
	UserID      pgtype.UUID
	KeyType     string
	KeyBlob     string
	Fingerprint string
}

func (q *Queries) HostAccessKeys(ctx context.Context, targetID pgtype.UUID) ([]HostAccessKeysRow, error) {
	rows, err := q.db.Query(ctx, hostAccessKeys, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HostAccessKeysRow{}
	for rows.Next() {
		var i HostAccessKeysRow
		if err := rows.Scan(
			&i.UserID,
			&i.KeyType,
			&i.KeyBlob,
			&i.Fingerprint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
